name: jmaker_qrscanner_mobile
description: "A mobile application for the qrcode scanner."
version: 1.5.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  syncfusion_flutter_datagrid: ^25.1.42
  syncfusion_flutter_datagrid_export: ^25.1.42
  syncfusion_flutter_xlsio:
  collection: ^1.18.0
  path_provider: ^2.1.3
  auto_route: ^8.1.3
  encrypt: ^5.0.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  mvc_pattern: ^8.12.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/fonts/Nunito/
